added feature
ipa320/cob_perception_common pull request #91
Opened 2018-10-04 13:04 UTC by ipa-fog

2018-11-22 20:56 UTC, fmessmer requested changes

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/src/ipa_3d_fov_visualization.cpp
> +#include <visualization_msgs/Marker.h>
please stick with the `<>` style

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/src/ipa_3d_fov_visualization.cpp
> +#include "sensor_msgs/Joy.h"
remove Float32 and Joy - not used

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/package.xml
> +  <exec_depend>visualization_msgs</exec_depend>
cleanup dependencies
- remove std_msgs
- use `depend` to collapse duplicates

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/package.xml
> +  <version>0.0.0</version>
set to current version of other packages

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +
add install tags

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +target_link_libraries(ipa_3d_fov_visualization ${catkin_LIBRARIES} ${WIRINGPI_LIBRARY})
what is WIRINGPI_LIBRARY?

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +
add_dependency to catkin_EXPORTED_TARGETS

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +)
`catkin_package()` is fine

2018-11-22 20:56 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +            visualization_msgs
sync with cleaned up package.xml

2018-11-22 20:56 UTC, fmessmer commented on cob_object_detection_visualizer/ros/src/object_detection_visualizer_node.cpp
> +        //cv::imshow("object detections", display);
please undo/remove from this PR

2018-11-26 17:42 UTC, fmessmer submitted a review, later dismissed

2018-11-26 17:42 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +
add_dependenies goes **before** target_link_libraries

2018-11-26 17:42 UTC, fmessmer commented on cob_object_detection_visualizer/ros/src/object_detection_visualizer_node.cpp
> +        cv::imshow("object detections", display);
undo indentation change

2018-11-26 17:42 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +
install launch folder

2018-11-27 10:07 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +
now its a duplicate line...remove below

2018-11-27 10:08 UTC, fmessmer commented on cob_object_detection_visualizer/ros/src/object_detection_visualizer_node.cpp
> +        cv::imshow("object detections", display);
stick with tabs

2019-01-09 17:01 UTC, ipa-rmb requested changes
Great contribution, thanks! Please make the two requested changes so that we can accept the PR.

2019-01-09 17:01 UTC, ipa-rmb commented on ipa_3d_fov_visualization/CMakeLists.txt
> +add_dependencies(ipa_3d_fov_visualization ${catkin_EXPORTED_TARGETS})
Double occurence in line 23 -> delete

2019-01-09 17:01 UTC, ipa-rmb commented on cob_object_detection_visualizer/ros/src/object_detection_visualizer_node.cpp
> +        cv::imshow("object detections", display);
Line 243 and 268 still have spaces instead of tabs. Please go back to the original 2x tabs indentation.

2019-01-18 18:53 UTC, ipa-rmb commented on cob_object_detection_visualizer/ros/src/object_detection_visualizer_node.cpp
> +        cv::imshow("object detections", display);
Sorry, this line still has spaces, instead of 2 tabs.

2019-01-18 18:56 UTC, ipa-rmb submitted a review, later dismissed

2019-01-18 18:58 UTC, ipa-rmb commented
@fmessmer can you please approve the fixes? I would then do a squash merge, right?

2019-01-28 15:27 UTC, ipa-rmb commented
@fmessmer ping

2019-01-29 09:07 UTC, fmessmer reviewed
@ipa-fog @ipa-rmb 
I'm only commenting...feel free to merge any time

2019-01-29 09:07 UTC, fmessmer commented on ipa_3d_fov_visualization/CMakeLists.txt
> +
I'd still insist on the consistent order:
 - `add_executable`
 - `add_dependencies`
 - `target_link_libraries`

2019-01-29 09:07 UTC, fmessmer commented on ipa_3d_fov_visualization/package.xml
> +  <license>Fraunhofer IPA</license>
all licenses should be `Apache2`...see any other package
as you already use the proper license header

2019-01-29 13:05 UTC, ipa-rmb approved these changes

2019-01-29 13:16 UTC, merged